### PR TITLE
Support upm package

### PR DESCRIPTION
**Pull request by shiena**
image

### CODE REVIEW

**Comment by Inspiaaa** [comment]
Hi shiena,
Many thanks. Good idea, much appreciated!
I‘ll take a look at your two pull requests through the week and get back to you.

**Comment by shiena** [comment]
After supporting upm, you can install this library from [openupm](https://openupm.com/) by adding the same tag as the version in package.json.
Installing the library from openupm is very convenient because you can update it from the Package Manager.
See also https://openupm.com/docs/adding-upm-package.html

**Comment by shiena** [comment]
There are several ways to install the upm package, which is suitable for development as it can be edited by putting it in the Packages folder. Please see the project below. This is an example of placing a library that supports upm in the Packages folder.

https://github.com/shiena/UnityHFSMUseSample/tree/unityhfsm

**Comment by Inspiaaa** [comment]
That's a great idea!

It adds a bit of complexity to the project but makes it more accessible. I'll merge your pull request
Thanks a lot for your contribution and helping me make UnityHFSM better. 👍

**Pull request merged**
